name: Daily Pull

on:
  schedule:
    - cron: '0 6 */1 * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  updating-the-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4
         

      - name: update of data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .scripts/scraper.py

      - name: Configure Git
        run: |
          git config --local user.email "sudesh@sudesh.com"
          git config --local user.name "sudesh0sudesh"

      - name: Commit changes
        run: |
          git add --all
          git diff-index --quiet HEAD || git commit -m "[AUTO] update sponsor data $(date '+%Y-%m-%d %H:%M:%S')"
          
      - name: Push changes
        id: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Force push if previous push failed
        if: failure()
        run: |
          git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
